
name: tvaux

services:
  fan-controller:
    build:
      context: fan-controller
    restart: unless-stopped
    # for access to /sys
    privileged: true
    volumes:
      - config:/config
    environment:
      - CONFIG_FILE=/config/fan-controller.yaml
      - MQTT_HOST=xxx

  cec-bridge:
    build:
      context: cec-bridge
    restart: unless-stopped
    # for access to CEC dongle
    privileged: true

  ps5-monitor:
    build:
      context: ps5-monitor
    restart: unless-stopped
    environment:
      - PS5_HOST=xxx
      - MQTT_HOST=xxx

  androidtv-monitor:
    build:
      context: androidtv-monitor
    restart: unless-stopped
    volumes:
      - config:/config
    environment:
      - ANDROIDTV_HOST=xxx
      - MQTT_HOST=xxx

  streaming:
    build:
      context: streaming-monitor
    restart: unless-stopped
    environment:
      - SWITCH_HOST=xxx
      - MONITORED_PORT=xxx
      - MQTT_HOST=xxx
      - SNMP_COMMUNITY=public

volumes:
  config:
