# PID sample interval in seconds
sample_interval: 2
heat_pressure_srcs:
  - name: AVReceiver
    wildcard_path: /sys/class/hwmon/hwmon1/temp2_input
    PID_params:
      set_point: 40
      P: -0.02
      I: -0.001
      D: -0.003


  - name: PlayStation
    wildcard_path: /sys/class/hwmon/hwmon1/temp1_input
    PID_params:
      set_point: 32
      P: -0.005
      I: -0.001
      D: -0.003

fans:
  - name: ps_bottom
    wildcard_path: /sys/class/hwmon/hwmon1/pwm1
    pwm_modes:
      manual: 1
      auto: 5
      pwm_mode_wildcard_path: /dev/null
    min_pwm: 25
    max_pwm: 255
    heat_pressure_srcs:
      - PlayStation
  - name: ps_top
    wildcard_path: /sys/class/hwmon/hwmon1/pwm3
    pwm_modes:
      manual: 1
      auto: 5
      pwm_mode_wildcard_path: /dev/null
    min_pwm: 25
    max_pwm: 255
    heat_pressure_srcs:
      - PlayStation
  - name: avr_bottom
    wildcard_path: /sys/class/hwmon/hwmon1/pwm2
    pwm_modes:
      manual: 1
      auto: 5
      pwm_mode_wildcard_path: /dev/null
    min_pwm: 25
    max_pwm: 255
    heat_pressure_srcs:
      - AVReceiver
  - name: avr_top
    wildcard_path: /sys/class/hwmon/hwmon1/pwm4
    pwm_modes:
      manual: 1
      auto: 5
      pwm_mode_wildcard_path: /dev/null
    min_pwm: 25
    max_pwm: 255
    heat_pressure_srcs:
      - AVReceiver

